language: julia
os:
  - linux
#   - osx # Disable to speed up CI. PolyJuMP has no binary dependency so the
          # result with osx and linux should be similar.
  - osx
julia:
  - 1.0
  - 1.1
notifications:
  email: false
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("PolyJuMP")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
